Dev
vaishnavme/IcyUi pull request #1
Opened 2021-03-24 07:17 UTC by vaishnavme

##### Imp:  Sidebar Bug Fix
- Responsive design
- Code examples

2021-03-24 16:48 UTC, villdev commented on index.html
> +				<div id="sidebar-content" class="sidebar-content">
Should the class not be `sidebar__content` ? In line with `sidebar__header`.

2021-03-24 16:50 UTC, villdev commented on index.html
> +						<input class="link__box" type="text" readonly value="&lt;link rel='stylesheet type='text/css' href='path_to/css'&gt;">
Does this link work as expected? Doesn't show correct one in sandbox

2021-03-24 16:51 UTC, villdev commented on js/app.js
> +window.addEventListener("scroll", event => {
Doesn't work for the modal link in sidebar.

2021-03-24 16:56 UTC, villdev reviewed
Great work! That's all I could find at a glance.

2021-03-24 16:56 UTC, villdev commented on index.html
> +				<div id="sidebar-content" class="sidebar-content">
Should the class not be `sidebar__content` ? In line with `sidebar__header`.

2021-03-24 16:56 UTC, villdev commented on index.html
> +						<input class="link__box" type="text" readonly value="&lt;link rel='stylesheet type='text/css' href='path_to/css'&gt;">
Does this link work as expected? Doesn't show correct one in sandbox

2021-03-24 16:56 UTC, villdev commented on js/app.js
> +window.addEventListener("scroll", event => {
Doesn't work for the modal link(last one) in sidebar.

2021-03-24 16:56 UTC, villdev commented on style/main.css
> +.sidebar-content li a.current {
Maybe make the active class(`.current`) more emphasized imo. Upto you though.

2021-03-24 18:24 UTC, amansethi00 reviewed
Great work Vaishnav ,class naming is consistent throughout the code

2021-03-24 18:24 UTC, amansethi00 commented on style/main.css
> +.color__block {
```suggestion
.color__block {
Class name do not go handy with the properties inside,name maybe w80-h50-card,feel free to choose any other name 
```

2021-03-24 18:24 UTC, amansethi00 commented on style/main.css
> +.status-idl {
go with status-warning name instead status-id1,as it will look consistent

2021-03-30 16:17 UTC, im-rhlrvndrn requested changes

2021-03-30 16:17 UTC, imrhlrvndrn commented on index.html
> +		<section id="container" class="container">
change thsi tag

2021-03-30 16:17 UTC, im-rhlrvndrn commented on style/main.css
> +.label-bell {
Update the names

2021-05-06 18:10 UTC, merged